// src/pages/voting.jsx
import React from 'react';
import Layout from '@theme/Layout';

function Services() {
    return (
        <Layout title="Voting">
            <div
                style={{
                    display: 'flex',
                    justifyContent: 'center',
                    alignItems: 'center',
                    fontSize: '20px',
                    padding: '10px'
                }}>
                <p>
                    <h2>Voting</h2>
                    <h3>How to Vote</h3>
                    <p>Just show up, show your citizen ID, and select your canidate.</p>
                    <h3>Local Elections:</h3>
                    <ul>
                        <li>Legal Review Board: August 5, 2020</li>
                        <ul>
                            <li>Dennis Alvarez</li>
                            <li>Raymond Alvarado</li>
                            <li>Nicholas Boyd</li>
                            <li>Gerald Ortiz</li>
                            <li>Roy Soto</li>
                            <li>Arthur Rogers</li>
                            <li>Gerald West</li>
                            <li>Dennis Murphy</li>
                            <li>Roger Franklin</li>
                            <li>Carl Coleman</li>
                            <li>Justin Harvey</li>
                            <li>Nicholas Ryan</li>
                            <li>Alexander Santos</li>
                            <li>Jeffrey Jimenez</li>
                            <li>Jacob Snyder</li>
                            <li>Jordan Cunningham</li>
                            <li>Carolyn Vasquez</li>
                            <li>Carolyn Vasquez</li>
                            <li>Doris Estrada</li>
                            <li>Maria Lee</li>
                            <li>Marilyn King</li>
                            <li>Christopher Hughes</li>
                            <li>Thomas Holmes</li>
                            <li>Robert Mayer</li>
                            <li>Matthias Adam</li>
                            <li>Marius Pedersen</li>
                            <li>Lucas Moulin</li>
                            <li>James Burke</li>
                        </ul>
                        <li>SamuelVille Judge: August 5, 2020</li>
                        <ul>
                            <li>Adam Contreras</li>
                            <li>Julia Davidson</li>
                        </ul>
                    </ul>
                </p>
            </div>
        </Layout>
    );
}

export default Services;

// src/views/Voting.vue
<template>
    <div class="page">
        <h2>Voting</h2>
        <h3>How to Vote</h3>
        <p>Just show up, show your citizen ID, and select your canidate.</p>
        <h3>Local Elections:</h3>
        <ul>
            <li>Legal Review Board: August 5, 2020</li>
            <ul>
                <li>Dennis Alvarez</li>
                <li>Raymond Alvarado</li>
                <li>Nicholas Boyd</li>
                <li>Gerald Ortiz</li>
                <li>Roy Soto</li>
                <li>Arthur Rogers</li>
                <li>Gerald West</li>
                <li>Dennis Murphy</li>
                <li>Roger Franklin</li>
                <li>Carl Coleman</li>
                <li>Justin Harvey</li>
                <li>Nicholas Ryan</li>
                <li>Alexander Santos</li>
                <li>Jeffrey Jimenez</li>
                <li>Jacob Snyder</li>
                <li>Jordan Cunningham</li>
                <li>Carolyn Vasquez</li>
                <li>Carolyn Vasquez</li>
                <li>Doris Estrada</li>
                <li>Maria Lee</li>
                <li>Marilyn King</li>
                <li>Christopher Hughes</li>
                <li>Thomas Holmes</li>
                <li>Robert Mayer</li>
                <li>Matthias Adam</li>
                <li>Marius Pedersen</li>
                <li>Lucas Moulin</li>
                <li>James Burke</li>
            </ul>
            <li>SamuelVille Judge: August 5, 2020</li>
            <ul>
                <li>Adam Contreras</li>
                <li>Julia Davidson</li>
            </ul>
        </ul>
    </div>
</template>
